jobs:
  workflow:
    name: Verify
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Fetch Libraries
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Unit Tests
        run: ./verify/ci

name: Ci

on:
  schedule:
    - cron: "10 2/3 * * *"
